### ISSUE TITLE
JDBC drivers error (web console)

### ISSUE THREAD

**Issue by gennari-dkt** [jboss-dockerfiles/wildfly#111]
Hi there,
i tried to create a docker image with these commands:

```
FROM jboss/wildfly:16.0.0.Final
RUN /opt/jboss/wildfly/bin/add-user.sh admin xxxxxxx --silent
CMD ["/opt/jboss/wildfly/bin/standalone.sh", "-b", "0.0.0.0", "-bmanagement", "0.0.0.0"]

```
and also with version 18

```
FROM jboss/wildfly:18.0.0.Final
RUN /opt/jboss/wildfly/bin/add-user.sh admin xxxxxxx --silent
CMD ["/opt/jboss/wildfly/bin/standalone.sh", "-b", "0.0.0.0", "-bmanagement", "0.0.0.0"]
```

When I try to access to Configuration->Subsytems->Datasources & Drivers->JDBC Drivers section I get the following error:

![image](https://user-images.githubusercontent.com/54432250/66459289-08218b00-ea75-11e9-9e43-523bd5e805af.png)

Same thing if I try to deploy a driver like PostgreSQL JDBC.

In version Wildfly 16.0.0.Final standalone (not docker) I do not have this error.

Can you help me please.

Very kind regards.

Alessio

**Comment by gabrielofers** [comment]
I have the same problem!

any news?

**Comment by FravashY** [comment]
Same error here.
