### ISSUE TITLE
Please update for Widlfly 19.1.0.Final

### ISSUE THREAD

**Issue by albers** [jboss-dockerfiles/wildfly#117]
Wildfly 19.1.0.Final was released on May 04, 2020, see [release announcement](https://wildfly.org/news/2020/05/04/WildFly-1910-Released/).

In contrast to previous updates, the Docker image [jboss/wildfly](https://hub.docker.com/r/jboss/wildfly) was not updated.

**Comment by jcputney** [comment]
@albers looks like the update got merged yesterday, should be all set

**Comment by albers** [comment]
Yes, the Docker image is available now. Thanks @jcputney
