### ISSUE TITLE
Upgrade to openjdk 11.0.8 cause application dead loop

### ISSUE THREAD

**Issue by andre-kornetzky** [jboss-dockerfiles/wildfly#122]
Can you please increase the openjdk version to 11.0.8+ ?
Our server has problems with TLS 1.3.

Further information under the following links:
https://stackoverflow.com/questions/54485755/java-11-httpclient-leads-to-endless-ssl-loop
https://bugs.openjdk.java.net/browse/JDK-8241054

Many thanks

**Comment by goldmann** [comment]
Builds are in progress! Thanks!
