### ISSUE TITLE
[QUESTION] Raspberry Pi 4 4Gb Docker

### ISSUE THREAD

**Issue by himuura** [jboss-dockerfiles/wildfly#128]
Im trying to get the image running on a Docker from Raspberry Pi 4 (ARM). Is it compatible or doable?
Getting the error "standard_init_linux.go:211: exec user process caused "exec format error"" that might be related to the architecture (x64 vs ARM).

**Comment by fabianfrz** [comment]
You probably need a JDK/JRE ARM image and then build the WildFly container on top of that. Then it should work. You cannot run a x86_64 image on ARM (except if your run it in qemu or something like that)

**Comment by t1** [comment]
It's actually possible to provide images in multiple architectures. [this](https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/) is a good explanation. I just opened issue #155.

It would be nice for MacBook M1 machines, too. Even though Docker Desktop supports emulation under the hood, it's very slow.

**Comment by t1** [comment]
I've also created a corresponding issue https://github.com/bitnami/bitnami-docker-wildfly/issues/76

**Comment by jmesnil** [comment]
I'm closing this as it has been fixed by https://github.com/jboss-dockerfiles/wildfly/pull/161
