### ISSUE TITLE
[QUESTION] will 21.0.1 be dockerized officially?

### ISSUE THREAD

**Issue by odemura** [jboss-dockerfiles/wildfly#130]
the latest docker image available today (2020-12-02) is `21.0.0.Final` from a month ago (2020-10-21) `jboss/wildfly:21.0.0.Final`
while the latest wildfly release is `21.0.1.Final` from 2020-11-19.
among others, it fixes 
[WFLY-13988](https://issues.redhat.com/browse/WFLY-13988) Missing dependency org.jboss.threads in org.infinispan module
[WFLY-13997](https://issues.redhat.com/browse/WFLY-13997) [21.x] Module org.infinispan is missing the org.jboss.threads dependency
which prevent using `infnispan-jcache` with wildfly-21.0.0.Final
(alternatively, the following code will fail in a war replayed to wildfly-21.0.0.Final
even when both `org.infinispan` and `org.jboss.threads` are listed as war module dependencies in `jboss-deployment-structure.xml`:
`org.infinispan.factories.threads.CoreExecutorFactory.executorFactory(4, 4, false)`)

**Comment by goldmann** [comment]
Closing this ticket, #129 was just merged.
