### ISSUE TITLE
Please update for Wildfly 21.0.2.Final

### ISSUE THREAD

**Issue by odemura** [jboss-dockerfiles/wildfly#132]
wildfly 21.0.2.Final was released on Dec 16, 2020, see [release announcement](https://issues.redhat.com/secure/ReleaseNote.jspa?projectId=12313721&version=12352600).
it has a critical bug fix [WFLY-14118](https://issues.redhat.com/browse/WFLY-14118) Distributed session manager can throw UnsupportedOperationException on concurrent calls to HttpServletRequest.getSession(...) for a given session

in contrast to previous updates, the Docker image jboss/wildfly was not updated.

[the pull request](https://github.com/jboss-dockerfiles/wildfly/pull/131) created using [Upgrade WildFly to 21.0.1.Final #129](https://github.com/jboss-dockerfiles/wildfly/pull/129) as a reference.

**Comment by goldmann** [comment]
Things are in queue for building, sorry for the delay!
