### ISSUE TITLE
 Wildfly usability

### ISSUE THREAD

**Issue by gabrielteixeira1912** [jboss-dockerfiles/wildfly#133]
how do i use the image of jboss / wildfly with jdk8 ??

**Comment by albers** [comment]
The image is not meant to be used with other JDKs than the one included in it.

Try building your own image using the [Dockerfile from this repository](https://github.com/jboss-dockerfiles/wildfly/blob/master/Dockerfile) but with the first instruction changed to `FROM jboss/base-jdk:8`.
