### ISSUE TITLE
Please update Dockerhub to WildFly 24.0.1.Final

### ISSUE THREAD

**Issue by p1ngod** [jboss-dockerfiles/wildfly#145]
As mentioned in PR https://github.com/jboss-dockerfiles/wildfly/pull/143 you released the Dockerfile for 24.0.1.Final on July 29, but the build job was not triggered manually.

Could you please queue the build so https://hub.docker.com/r/jboss/wildfly/ is up to date again?

Thanks in advance!

**Comment by p1ngod** [comment]
@jmesnil @goldmann does one of you have a chance to trigger the Dockerhub build?
Sorry to bug you directly :-/

**Comment by jmesnil** [comment]
@goldmann, I don't have permission to trigger the DockerHub build. If you grant it to me (and show me how to do it), I can take over that part when we release new WildFly versions.

**Comment by goldmann** [comment]
After changes made to Docker HUB account types we are currently unable to:

1. Grant new permissions.
2. Trigger any builds from the UI.

A new system needs to be put into place to make it work again. Potentially GitHub actions with a push to HUB/Quay.

**Comment by p1ngod** [comment]
Any chance to support you guys with this?

**Comment by p1ngod** [comment]
> 
> 
> A new system needs to be put into place to make it work again. Potentially GitHub actions with a push to HUB/Quay.

@goldmann I've prepared a release workflow for publishing the image to DockerHub and Quay.io following https://docs.github.com/en/actions/guides/publishing-docker-images#publishing-images-to-docker-hub-and-github-packages and testing with own docker repos at https://hub.docker.com/r/p1ngod/wildfly/tags?page=1&ordering=last_updated and https://quay.io/repository/kinzel/wildfly?tab=tags

I would like to create a PR from https://github.com/p1ngod/wildfly if that's an acceptable solution for you. (of course with the right repos to push at)

**Comment by jmesnil** [comment]
This looks good to me.

@p1ngod Pushing to DockerHub is enough. I'm not sure we want to provide the same images on quay.io (unless @goldmann wants to).

With that GitHub Action, all we'd need is push a tag after a PR is merged to release the Docker image with that tag (and `latest`).

**Comment by p1ngod** [comment]
@jmesnil the trigger is currently called on releases rather than created tags. Could you tell me how you create the releases on GitHub as they seem to be a little bit different from my manually created release in the test repo? Alternatively, I could change it to listening on tag publishes.

**Comment by jmesnil** [comment]
@p1ngod your action is fine to trigger on releases. GitHub automatically creates releases based on tags anyway.

**Comment by p1ngod** [comment]
@jmesnil nope, just tried it out. It's listed on https://github.com/p1ngod/wildfly/releases but not triggered by the release-hook.
I've tested it via tags in https://github.com/p1ngod/wildfly/blob/0d11c304768a9bf6a96053c404d25e0fbb7b7aeb/.github/workflows/publish-release.yml#L2-L5 and that works as expected.

Will provide a PR with this solution asap.

**Comment by p1ngod** [comment]
any updates on this?

**Comment by goldmann** [comment]
Oh, I thought made you admin already! Granted access now!

**Comment by asbachb** [comment]
Seems that WildFly 25 was released, but no official docker image is available.

**Comment by jmesnil** [comment]
@asbachb We are having issues with new limitations on DockerHub but are working on it (tracked by https://github.com/jboss-dockerfiles/wildfly/pull/147)
