### ISSUE TITLE
Wildfly 25 with jdk 17 base image

### ISSUE THREAD

**Issue by hawlik** [jboss-dockerfiles/wildfly#148]
Hi,
as Wildfly 25 comes with official support for java 17 it would be great if we would have docker image with this setup available.

I can provide some PR if that might help.

cheers
Tomasz

**Comment by andre-kornetzky** [comment]
I miss this feature too!

**Comment by chrispoulsen** [comment]
Java 17 has been available for almost 6 months now...

**Comment by OrcunColak** [comment]
Add Wildfly 25 with jdk 17 base image please

**Comment by jmesnil** [comment]
I'm closing this as it has been "fixed" by https://github.com/jboss-dockerfiles/wildfly/pull/161.
We have published WildFLy 26 images for JDK 17
