### ISSUE TITLE
base OS image is old for wildfly

### ISSUE THREAD

**Issue by ajay-aggarwal** [jboss-dockerfiles/wildfly#149]
It seems the wildfly image is still using an older version of CentOS 7 (centos 7.8.2003) which has too many open CVEs. Is there a plan to update to a more recent base OS image?

**Comment by VORUSRIK000** [comment]
Tagging on to the question. We have many active security errors identified in our deployment related to the old packages referred. Would appreciate if anyone can provide an update on the plan/roadmap for the OS image upgrade.

**Comment by jmesnil** [comment]
I'm closing this as it has been fixed by https://github.com/jboss-dockerfiles/wildfly/pull/161
