### ISSUE TITLE
Get permission denied error

### ISSUE THREAD

**Issue by haiiro-shimeji** [jboss-dockerfiles/wildfly#15]
I tried the following command to start a wildfly instance, but I got a permission denied error.

> $ docker run -it jboss/wildfly
> 2015/03/11 05:55:42 permission denied

I can start the instance with -u root option, but the Dockerfile intends to run the program as jboss user.
I wonder the jboss user should be able to log in to execute the command.
Now, jboss user's login shell is /sbin/nologin.

> $ docker run -it -u root jboss/wildfly grep jboss /etc/passwd
> jboss :x :1000:1000:JBoss user:/opt/jboss:/sbin/nologin

**Comment by goldmann** [comment]
I have a feeling that the downloaded image or the Docekr environment is corrupted on your end, but to start debugging this I would need some info:

```
$ docker info
$ docker -v
$ docker images jboss/wildfly
```

**Comment by haiiro-shimeji** [comment]
Thanks.
This is my environment.

```
$ docker info
Containers: 28
Images: 396
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Dirs: 452
Execution Driver: native-0.1
Kernel Version: 3.13.0-46-generic
WARNING: No swap limit support

$ docker -v
Docker version 0.9.1, build 3600720

$ docker images jboss/wildfly
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
jboss/wildfly       8.2.0.Final         24c5b96027df        3 months ago        951.3 MB
jboss/wildfly       latest              0cc86be8ac93        3 months ago        951.3 MB
jboss/wildfly       8.1.0.Final         502c663d30ad        3 months ago        948.7 MB
```

I removed jboss* images and do the following.
```
$ docker run -it jboss/wildfly
```
But got a same error..

**Comment by goldmann** [comment]
Oh, you use a very, very old version of Docker, please upgrade to latest version.

**Comment by haiiro-shimeji** [comment]
Thanks.
So sorry.. I was using the docker version that is provided by ubuntu trusty repository.
Now, I'm using docker version 1.5.0 and it works fine.

Thanks for your help!
