### ISSUE TITLE
When will the WildFly 25.0.1 docker image be released to docker hub?

### ISSUE THREAD

**Issue by fisco-unimatic** [jboss-dockerfiles/wildfly#153]
[WildFly 25.0.1 was released](https://www.wildfly.org/news/2021/11/04/WildFly2501-Released/) on November 4th, and the [dockerfile was tagged for 25.0.1.Final](https://github.com/jboss-dockerfiles/wildfly/releases/tag/25.0.1.Final) on 22nd November.
When will the corresponding docker image be released to [docker hub](https://hub.docker.com/r/jboss/wildfly/tags)?
Is this the right place to ask?

**Comment by goldmann** [comment]
It's available on quay from now on: https://quay.io/repository/wildfly/wildfly?tag=latest&tab=tags

**Comment by fisco-unimatic** [comment]
Thanks @goldmann. That works for me.
