### ISSUE TITLE
Create arm64 Images

### ISSUE THREAD

**Issue by t1** [jboss-dockerfiles/wildfly#155]
For all Raspberry Pie ARM and MacBook Pro M1/Pro/Max users, it would be very nice to have these images not only for `linux/amd64`, but also at least for `linux/arm64`. This cascades down to the base CentOS, which is available for even more achitectures.

It would be also possible to support Windows as OS, but I guess that would be a separate issue.

**Comment by t1** [comment]
I'm not sure if this is actually being built with GitHub Actions or not, as there's already some setup for `buildx` but also a `cccp.yml` file. This works for me:

`docker buildx build --push --platform linux/arm64,linux/amd64 -t <owner>/wildfly .`

**Comment by amoscatelli** [comment]
We are moving our architecture to arm64 and we also need this.
Any plans for arm64?

**Comment by amoscatelli** [comment]
@t1 I don't understand, how can you build wildfly image for arm64 ?
Wildfly Dockerfile is based on jboss/base-jdk:11 which is not arm64 compatible.

**Comment by t1** [comment]
This propagates from `jboss/wildfly` → `jboss/base-jdk` → `jboss/base` → `centos:7`, which is finally available also for `arm64`.

**Comment by amoscatelli** [comment]
@t1 I spent some hour trying to figure out how to make this work on arm64 machine.

I cloned https://github.com/jboss-dockerfiles/wildfly.git.
I ran 'docker buildx build --push --platform linux/arm64 -t visiontechcloud/wildfly .' inside the folder.
The image is public/published here :
https://hub.docker.com/r/visiontechcloud/wildfly

![image](https://user-images.githubusercontent.com/16684470/156604781-c2e47744-ad25-4112-b812-8d0a6798bb49.png)

Then I tried a simple 'docker run visiontechcloud/wildfly' on an aarch64 (aarch64 = arm64 afaik) machine and I got this error 
service_1  | standard_init_linux.go:228: exec user process caused: exec format error

Feels like I misenderstood something important.
This kind of errors usually happen when a non arm image is run on arm64 architecture.

**Comment by t1** [comment]
That works on my M1, but it's kinda slow. I have no idea what the cause of your problem could be.

FYI: I build by own images and publish them as https://hub.docker.com/repository/docker/rdohna/wildfly It would be just very nice if the 'official' wildfly images where multi-arch.

**Comment by amoscatelli** [comment]
The compressed image is different also. I am really doing something wrong ...
I am going to test your images.
Also, I am running the 'docker buildx build' command on windows. Are you building on Linux ?

**Comment by amoscatelli** [comment]
Also your Dockerfile is also different :
https://github.com/t1/rdohna-wildfly-docker-image/blob/master/Dockerfile

Mine is the original from :
https://github.com/jboss-dockerfiles/wildfly/blob/master/Dockerfile

**Comment by t1** [comment]
I'm building on a M1 Mac. That's why I need arm images. My build is completely different, yes. I currently add variants that include the GraphQL feature pack.

**Comment by amoscatelli** [comment]
So you are building directly on ARM Machine, I am trying to build from x64 for Arm64 ... I thought that I could do that with buildx.
I am going to try and compile directly from an ARM Machine too then.

**Comment by t1** [comment]
I build x64 images from my arm machine, so it should go the other way around, too. But I haven't tried that.

**Comment by t1** [comment]
BTW: I also build the images via GitHub Actions, and they seem to run x64... works just fine, too.

**Comment by krisgerhard** [comment]
I've created a PR https://github.com/jboss-dockerfiles/wildfly/pull/157 to build arm64 image in addition to amd64.
ARM64 images need to be built for `base` and `base-jdk` as well though which are not maintained through GitHub Actions so I have no way to influence those.

**Comment by krisgerhard** [comment]
In the meantime you can use the images we built for ourselves.

Available platforms: linux/arm64 linux/amd64
Wildfly (last 9 releases): https://hub.docker.com/r/cybexer/wildfly/tags
Base-jdk (all tags): https://hub.docker.com/r/cybexer/base-jdk/tags
Base (all tags): https://hub.docker.com/r/cybexer/base/tags

**Comment by amoscatelli** [comment]
Thank you.
Anyway we hope to get soon official images to migrate also Keycloak images to arm64.

**Comment by krisgerhard** [comment]
🤞

**Comment by jmesnil** [comment]
thanks to @krisgerhard, we now have linux/arm64 image starting with quay.io/wildfly/wildfly:26.1.1.Final-2.

**Comment by krisgerhard** [comment]
> I've created a PR #157 to build arm64 image in addition to amd64. ARM64 images need to be built for `base` and `base-jdk` as well though which are not maintained through GitHub Actions so I have no way to influence those.

@jmesnil Thank you for merging. Unfortunately this is only one piece of the puzzle. Underlying images `base` and `base-jdk` also need to be built for ARM64. Can you elevate this issue?

**Comment by jmesnil** [comment]
@krisgerhard oh, sorry, I thought the base images were already supporting the arm64 architecture but that were your forks...

I'll check what can be done with the base-jdk images. I also wonder if that's not the right opportunity to switch to the official openjdk images that are more often updated....

**Comment by jmesnil** [comment]
arm64 supported in `base-jdk` tracked by https://github.com/jboss-dockerfiles/base-jdk/issues/19

**Comment by amoscatelli** [comment]
@krisgerhard maybe you could make a PR from your fork also for base-jdk ?

thank you in advance

**Comment by krisgerhard** [comment]
> @krisgerhard maybe you could make a PR from your fork also for base-jdk ?
> 
> thank you in advance

Underlying images are not built via Github Actions unfortunately.

**Comment by amoscatelli** [comment]
Oh, I see.
I hope we get lucky 😢

**Comment by krisgerhard** [comment]
I would welcome merging https://github.com/jboss-dockerfiles/wildfly/pull/161. It uses base image which supports both arm and amd architectures.

**Comment by jmesnil** [comment]
I'm closing this as it has been fixed by https://github.com/jboss-dockerfiles/wildfly/pull/161
