### ISSUE TITLE
Centos7

### ISSUE THREAD

**Issue by jin-harmoney** [jboss-dockerfiles/wildfly#168]
Any reason why `centos7` is still used?

Scan result of `Wildfly 26.1.2`.Final on `eclipse-temurin:17-centos7` (the one used in this repo):

![image](https://user-images.githubusercontent.com/73221968/211579275-6385bccf-63f4-4558-8e8c-f7674bb4e1b3.png)

Compared to `Wildfly 26.1.2`.Final on `eclipse-temurin:17-jre`:

![image](https://user-images.githubusercontent.com/73221968/211579723-b78cb369-7269-4496-aa4a-d9c2a336f7e0.png)

**Comment by aairey** [comment]
Please see #194 also.

**Comment by jmesnil** [comment]
closed by #194
