### ISSUE TITLE
Java 8 tags?

### ISSUE THREAD

**Issue by sixcorners** [jboss-dockerfiles/wildfly#18]
The way that [the maven docker repo](https://registry.hub.docker.com/_/maven/) does their tags is that they have different tags for different versions of java. Would that be a good fit for the wildfly docker repo?

**Comment by goldmann** [comment]
Currently we ship WildFly only with JDK 8. Of course this can change in the future. When we'll have a better builder (and not Docker HUB) - we'll probably add these tags. Currently there is too much pain to keep stuff like this in sync.

**Comment by sixcorners** [comment]
I could have sworn when I posted this it was using 7. If it only ships with JDK 8 that's ok with me.
