### ISSUE TITLE
Provide support JDK 17 with UBI 9 image 

### ISSUE THREAD

**Issue by voltor** [jboss-dockerfiles/wildfly#194]
From README
![image](https://github.com/jboss-dockerfiles/wildfly/assets/26440987/1cee2d09-a365-4be0-959e-6ab362271027)

Actually [eclipse-temurin](https://hub.docker.com/_/eclipse-temurin/tags) has UBI 9 images with java 17
it will make opportunity to stay on JDK 17 and migrate from CentOS with minimal risk

**Comment by jmesnil** [comment]
+1, I want to communicate this to the WildFly community and align it with the upcoming WildFly 33 release.
