### ISSUE TITLE
no package manager installed for quay.io/wildfly/wildfly:32.0.0.Final-2-jdk21

### ISSUE THREAD

**Issue by sare3th** [jboss-dockerfiles/wildfly#199]
Hi,
I am migrating a Dockerfile that was previously based on jboss/wildfly:23.0.0.Final
I'm migrating to quay.io/wildfly/wildfly:32.0.0.Final-2-jdk21.

I noticed that yum/dnf is not installed in this image. Is this intentional? If yes, what should I use instead?
![image](https://github.com/jboss-dockerfiles/wildfly/assets/31948203/301c18f6-a1dc-4472-b6f9-5818fdd77360)

**Comment by jmesnil** [comment]
The image is based on ubi9-minimal so you can use `microdnf` instead of yum/dnf
