### ISSUE TITLE
creating custom image from local installation

### ISSUE THREAD

**Issue by itsdpk** [jboss-dockerfiles/wildfly#30]
Hi i am trying to create a new image from my local jboss wildfly installation, can i tar it up and import as a docker image ? or how should this be made possible.

I had tried to tar and import, though the image was created i was getting error while running the image.
Error response from daemon: could not find command

Tried creating a dockerfile from scratch but while i build the same it was breaking on RUN with
[8] System error: exec: "/bin/sh": stat /bin/sh: no such file or directory
contents of dockerfile added below
FROM scratch
RUN tar xf ./wildfly.tar \
&& mv wildfly /opt/jboss/wildfly
ENV LAUNCH_JBOSS_IN_BACKGROUND true
EXPOSE 8080
CMD ["/opt/jboss/wildfly/bin/standalone.sh", "-b", "0.0.0.0", "-bmanagement", "0.0.0.0"]

any help would be much appreciated

**Comment by goldmann** [comment]
We do not provide help for custom images that do not base on `jboss/wildfly`, but...

You do not add the wildfly.tar package into the image in first place (`ADD` instruction). Additionally - you did not provide any log for the build step so it's hard to guess where the issue is.
