### ISSUE TITLE
Permission problem

### ISSUE THREAD

**Issue by pedro-hos** [jboss-dockerfiles/wildfly#31]
hi, i need help to run yum update and yum install maven. But when I run this command I need the root password. Somebody help me?

tks

**Comment by goldmann** [comment]
There is no `root` password. Please read a bit more about Docker. Hint: https://docs.docker.com/engine/reference/builder/#user and https://docs.docker.com/engine/reference/run/#user.

**Comment by cold-gin** [comment]
Hey why do you have to give him a "hint"? Why not just help him out, as his question is a valid one. 

For those who also ran into this issue, as I did, you need to run the USER command to switch user to root before your commands that require root. The base image's dockerfile sets the user to jboss and that's what you inherit. So after you specify FROM jboss/wildfly, at the point in the script where you need to install something, do:

RUN USER root 

then specify your install commands, and then follow that by 

RUN USER jboss 

to switch back to the jboss user that the base docker image had set. See this link for more clarity:

https://github.com/arun-gupta/docker-images/blob/master/wildfly-centos/Dockerfile

**Comment by goldmann** [comment]
I do not necessarily agree with you, but I thank you for stepping in and making it more clear. For me it's not a valid question for this specific project. Question is about basic Docker knowledge, that's why I left a hint and not a detailed answer. You know, giving a man a pole, not a fish.

**Comment by alexandreogrodovski** [comment]
Thank you @cold-gin
