### ISSUE TITLE
Unable to run yum

### ISSUE THREAD

**Issue by NickClark** [jboss-dockerfiles/wildfly#33]
Basing a custom docker image off of this one, I find that whenever I try to do a `yum install` it fails with 

```
Transaction check error:
  file /usr/lib64/libsystemd-daemon.so.0 from install of systemd-libs-219-19.el7.x86_64 conflicts with file from package systemd-container-libs-208.20-6.el7.centos.x86_64
  file /usr/lib64/libsystemd-id128.so.0 from install of systemd-libs-219-19.el7.x86_64 conflicts with file from package systemd-container-libs-208.20-6.el7.centos.x86_64
  file /usr/lib64/libsystemd-journal.so.0 from install of systemd-libs-219-19.el7.x86_64 conflicts with file from package systemd-container-libs-208.20-6.el7.centos.x86_64
  file /usr/lib64/libsystemd-login.so.0 from install of systemd-libs-219-19.el7.x86_64 conflicts with file from package systemd-container-libs-208.20-6.el7.centos.x86_64
  file /usr/lib64/libudev.so.1 from install of systemd-libs-219-19.el7.x86_64 conflicts with file from package systemd-container-libs-208.20-6.el7.centos.x86_64
  file /usr/lib64/security/pam_systemd.so from install of systemd-libs-219-19.el7.x86_64 conflicts with file from package systemd-container-libs-208.20-6.el7.centos.x86_64
```

**Comment by NickClark** [comment]
The latest centos 7.2 image resolves the issue for me. I Just went ahead and copied all the Dockerfile steps from this image and it's base images until this can be fixed

**Comment by amenophis** [comment]
Just need a rebuild and push to docker hub !
Please :)

**Comment by jruels** [comment]
Can we get an ETA on when this image will be rebuilt with centos 7.2 base?

**Comment by goldmann** [comment]
I'll do it today, sorry for the delay.

--Marek

/sent from my phone
20.01.2016 8:06 PM "Jason" <notifications@github.com> napisał(a):

**Comment by jruels** [comment]
Thanks for the quick response! 

Thanks,
-js

-- Typo’s courtesy of Apple --

On January 20, 2016 at 2:07:01 PM, Marek Goldmann (notifications@github.com) wrote:

I'll do it today, sorry for the delay.

--Marek

/sent from my phone
20.01.2016 8:06 PM "Jason" <notifications@github.com> napisał(a):

**Comment by goldmann** [comment]
New build is kicked, please try in a bit.

Closing this ticket as this should fix it. Feel free to reopen if it doesn't work for you.
