### ISSUE TITLE
Error in downloading the image

### ISSUE THREAD

**Issue by 64BitAsura** [jboss-dockerfiles/wildfly#4]
bash-3.2$ docker pull jboss/wildfly
Pulling repository jboss/wildfly
365390553f92: Error pulling image (latest) from jboss/wildfly, operation not supported ry-1.docker.io/v1/, operation not supported 
782cf93a8f16: Download complete 
7d3f07f8de5f: Download complete 
1ef0a50fe8b1: Download complete 
20a1abe1d9bf: Error downloading dependent layers 
2014/10/31 13:27:06 Error pulling image (latest) from jboss/wildfly, operation not supported
bash-3.2$

**Comment by Viciouss** [comment]
I'm getting a similar error with version 1.5.0 of docker, but it seems to fail earlier in the download process:

0cc86be8ac93: Error pulling image (latest) from jboss/wildfly, ApplyLayer exit status 1 stdout:  stderr: operation not permitted
 not permitted ownload complete
782cf93a8f16: Download complete
7d3f07f8de5f: Error downloading dependent layers
FATA[0005] Error pulling image (latest) from jboss/wildfly, ApplyLayer exit status 1 stdout:  stderr: operation not permitted


Docker version 1.5.0, build a8a31ef

Containers: 0
Images: 2
Storage Driver: devicemapper
 Pool Name: docker-8:1-535149-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 306.8 MB
 Data Space Total: 107.4 GB
 Metadata Space Used: 786.4 kB
 Metadata Space Total: 2.147 GB
 Udev Sync Supported: false
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.82-git (2013-10-04)
Execution Driver: native-0.2
Kernel Version: 3.10.9-xxxx-grs-ipv6-64
Operating System: Debian GNU/Linux 7 (wheezy)
