### ISSUE TITLE
Unable to redirect to Administration Console

### ISSUE THREAD

**Issue by a1exus** [jboss-dockerfiles/wildfly#45]
I'm trying to access Administration Console and getting following message:

> Unable to redirect.
> 
> An automatic redirect to the Administration Console is not currently available. This is most likely due to the administration console being exposed over a network interface different from the one to which you are connected to.
> 
> To access the Administration console you should contact the administrator responsible for this WildFly installation and ask them to provide you with the correct address.
> 

Please advise.

**Comment by a1exus** [comment]
After carefully re-reading everything, I found my answer under [Extending the image](https://hub.docker.com/r/jboss/wildfly/).

**Comment by zhongyu6666** [comment]
Can I ask how you solved it
