### ISSUE TITLE
running wilfly container on openshift origin, the user is however (100004000, root), rather than (jboss, jboss)

### ISSUE THREAD

**Issue by yu-shao-gm** [jboss-dockerfiles/wildfly#47]
I am running docker hub zanata/server which is based on wildfly container, after the application is up, the current running wildfly is (uid=1000040000, gid=0), it should be (jboss,jboss) to be able to access files correctly.

However, I could use following command with openshift to bypass the problem:
oc adm policy add-scc-to-user anyuid -z default

Fedora 24, Openshift: v1.3.1.

Thanks,
Shao

**Comment by goldmann** [comment]
This image is not meant to be used directly on OpenShift. You need to extend it and adjust for OpenShift, please take a look at this: https://docs.openshift.org/latest/creating_images/guidelines.html#openshift-origin-specific-guidelines

**Comment by rhuss** [comment]
@goldmann But would it be that harmful to add the user `jboss` to the root group, so that one could easily adapt images based on this image by tuning the group permissions so that it follows the guidelines mentioned above and can be adapted for OpenShift ?

**Comment by goldmann** [comment]
This can be modified in the upper layer too, very easily:

```
usermod -g root -G jboss jboss
```

**Comment by rhuss** [comment]
yes, if you change the user to 'root' before and then back to 'jboss' afterwards. Unfortunately its not yet possible for e.g docker-maven-plugin to change the user for running a command.

That's why I ask, whether it would harm to add this already in the base image before switching to user 'jboss'. It would safe two layers, too.
