### ISSUE TITLE
Upgrading to JDK 9?

### ISSUE THREAD

**Issue by fewi** [jboss-dockerfiles/wildfly#75]
Hello,
are there pans for upgrading the base image to JDK 9 for Wildfly12? 
Or do we have to wait for Wildfly 13?

**Comment by phillipjohnson** [comment]
Looks like this has been updated! I was able to get a JDK11 project running on the [15.0.0.Final-1 release](https://github.com/jboss-dockerfiles/wildfly/releases/tag/15.0.0.Final-1).

**Comment by goldmann** [comment]
That's correct! Thanks to the community contribution it was updated recently. I'm closing this ticket.
