### ISSUE TITLE
root password 

### ISSUE THREAD

**Issue by yahavb** [jboss-dockerfiles/wildfly#76]
I would install some tools in the image container and need the root password. 
`sudo` does not work when `exec`-ing to the container. 
What is the best way to do so?

**Comment by JsebExamotive** [comment]
Hello,

In the dockerfile you can use

USER root
... Your stuff here ...
USER jboss

Or you can run the container with the user root by adding USER root at the
end of your dockerfile but I do not recommand it.

Le jeu. 26 avr. 2018 à 20:04, Yahav Biran <notifications@github.com> a
écrit :

**Comment by FritschAuctores** [comment]
Dockerfile:
´´´
FROM jboss/wildfly:14.0.0.Final
USER root

RUN useradd myroot -m -s /bin/bash -g 0
RUN echo 12345 | passwd --stdin myroot

USER jboss
´´´

**Comment by xavs** [comment]
I think sudo should be enabled like in any other image out there

**Comment by FelipeRuizGarcia** [comment]
@xavs agree with u.

meanwhile my workaround is extend de Dockerfile like 

`FROM jboss/wildfly

USER root

RUN passwd --delete root

USER jboss

CMD ["/opt/jboss/wildfly/bin/standalone.sh", "-b", "0.0.0.0", "-bmanagement", "0.0.0.0"]
~                                                                                            `

**Comment by FelipeRuizGarcia** [comment]
Hi, I send a pull request that fix this error

https://github.com/jboss-dockerfiles/wildfly/pull/102

**Comment by goldmann** [comment]
Container images should never require `root` user access. In case you need to modify the image, create a new one based on this one. This is the proper workflow.

This image has a `root` account with undefined password, you cannot sudo into it as-is.

I'm sorry, but I need to close this issue.
