### ISSUE TITLE
non-zero code : 6

### ISSUE THREAD

**Issue by joeg-ita** [jboss-dockerfiles/wildfly#83]
System: ubuntu server 18.04.1 running on virtualbox
Dockerfile is the one provided on this repository

sudo docker build --tag=wf .
return the following error

![dwf](https://user-images.githubusercontent.com/25502936/45763761-76f53180-bc31-11e8-9963-b867e00833e7.PNG)

**Comment by goldmann** [comment]
This is an issue with your Docker host. Most probably wrong DNS configuration inside Docker.
