### ISSUE TITLE
Both Wildfly 15 images use jdk 11

### ISSUE THREAD

**Issue by amoscatelli** [jboss-dockerfiles/wildfly#90]
Dunno how is it possible, but even the jdk 8 version uses jdk 11 …

Is this my fault ?

**Comment by goldmann** [comment]
What do you mean by both images? WildFly 15 image is shipped with JDK 11, only.

**Comment by amoscatelli** [comment]
I looked like 15.0.0.Final was shipped jdk8 and 15.0.0.Final was shipped with jdk11.

**Comment by amoscatelli** [comment]
I misunderstood this : 

https://github.com/jboss-dockerfiles/wildfly/commit/f33ac339aab78959ef8374b4183a1c9e771a8789

Thank you for the clarification

**Comment by goldmann** [comment]
The -1 tag was a fix for the WildFly 15 release to base on JDK 11.
