### ISSUE TITLE
unable to login via CLI ?

### ISSUE THREAD

**Issue by Inkimar** [jboss-dockerfiles/wildfly#97]
Hi,

I am using this image as my base: 
`FROM jboss/wildfly:8.2.1.Final
`

here is my Dockerfile:
`https://github.com/Inkimar/dw-media_docker/blob/ingimar/upgrading-docker_for_vegadare/wildfly-custom/Dockerfile`

Everything runs fine.
Logging into my docker-container, navigating to '/opt/jboss/wildfly/bin' and running './jboss-cli.sh '
```
[root@9c4e61c84671 bin]# ./jboss-cli.sh 
Exception in thread "Thread-2" java.lang.RuntimeException: broken pipe
	at org.jboss.aesh.console.reader.ConsoleInputSession$2.run(ConsoleInputSession.java:91)
You are disconnected at the moment. Type 'connect' to connect to the server or 'help' for the list of supported commands.
```
I get the above exception, why am I not able to login to wildfly ?
I have been able to login before.

best, i

**Comment by montanero** [comment]
Same problem here. Perhaps something to do with operating system? Using Mint/Tara

**Comment by montanero** [comment]
Problem seems to be in the command line reader, but can use jboss-cli to execute commands directly
`
./jboss-cli.sh --connect controller=localhost:9989  '/subsystem=logging/logger=jboss.jdbc.spy/:add(level=TRACE)'
`

**Comment by jmesnil** [comment]
I can not reproduce with the latest image:

```
docker run -p 8080:8080 quay.io/wildfly/wildfly

docker exec -it thirsty_shannon /bin/bash
[jboss@c2b4d66388cc ~]$ $JBOSS_HOME/bin/jboss-cli.sh -c
[standalone@localhost:9990 /] version
JBoss Admin Command-line Interface
JBOSS_HOME: /opt/jboss/wildfly
Release: 18.1.1.Final
Product: WildFly Full 26.1.1.Final
JAVA_HOME: /usr/lib/jvm/java
java.version: 11.0.8
java.vm.vendor: Oracle Corporation
java.vm.version: 11.0.8+10-LTS
os.name: Linux
os.version: 5.10.104-linuxkit
```
